set -g default-terminal "screen-256color"
set -g mouse on

# notifications, progress updates should propagate
set -g allow-passthrough on

# allow distinguishing between shift+enter vs enter
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# pane movement
bind-key j command-prompt -p "join pane from:"  "join-pane -s '%%'"
bind-key s command-prompt -p "send pane to:"  "join-pane -t '%%'"
