set -g default-terminal "screen-256color"
set -g mouse on

# notifications, progress updates should propagate
set -g allow-passthrough on

# allow distinguishing between shift+enter vs enter
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
